default['teamcity-agent']['agent_name'] = "agent-1"
default['teamcity-agent']['win_agent_path'] = "c:\\tc"
default['teamcity-agent']['linux_agent_path'] = "/opt/teamcity"
default['teamcity-agent']['administrator-password'] = "testtest"
default['teamcity-agent']['rktools-url'] = "http://download.microsoft.com/download/8/e/c/8ec3a7d8-05b4-440a-a71e-ca3ee25fe057/rktools.exe"
